version: 2

project_name: hello-goreleaser

release:
  name_template: 'Amol {{.Version}}'
  prerelease: auto

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format_overrides:
      - goos: windows
        formats: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  use: github-native
